version: '3.8'

services:
    db:
        image: postgres:16
        container_name: projeto1_postgres
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: projeto1db
        volumes:
            - ./projeto_1:/projeto_1/
            - ./projeto_2:/projeto_2/
        ports:
            - "5432:5432"
        restart: unless-stopped
